### ISSUE TITLE
Kubelet fails to destroy network for container sandbox

### ISSUE THREAD

**Issue by muffin87** [projectcalico/calico#4084]
# Kubelet reports "failed to destroy network for sandbox" for calico 3.14.2+

## Expected Behavior
Kubelet/the container runtime should be able to destroy the network of an exited container and cleanup the sandbox.

## Current Behavior
After updating from calico 1.13.2 to 1.16.2, we noticed that Kubelet keeps spamming the following message:

```jsx
level=error msg="StopPodSandbox for \"4b84ed8e89e46cb78735cddc21208cb7bbe6d4959a0086a6aa0fa226bf9376e2\" failed" error="failed to destroy network for sandbox \"4b84ed8e89e46cb78735cddc21208cb7bbe6d4959a0086a6aa0fa226bf9376e2\": WorkloadEndpoint.crd.projectcalico.org \"WorkloadEndpoint(default/node01-k8s-prometheus--1-eth0)\" not found"
```
Looking at the running containers on the host, the sandbox is actually still there and cannot be removed. This seems to be the case only with statefulsets. Deployments work well.

## Steps to Reproduce
- Running calico 1.16.2
- Create a statefulset (even without actual state, doesn't matter)
- Delete the pod and make sure it moves to another node, so the WEP name changes
- Kubelet on the old node starts spamming the log message above

## Context
As already mentioned, the problem only occurs with statefulsets. However, it does NOT seem to be related to the actual statefulness of the Pods, but to the different naming of the statefulsets and thus the WEPs. Since we updated from 1.12.x directly to 1.16.x, we tried to find the latest version that still works. This was 1.13.x. Rolling back to 1.13.x fixes these error messages immediately and Kubelet is able to clean up the remaining sandboxes. So the problem seems to have been introduced with the update to 1.14.x.

## Your Environment
- Calico version: 1.16.2
- Orchestrator version: Kubernetes v1.18.8
- OS: CentOS 7 with Kernel 5.7.6
- Container Runtime: containerd v1.4.0
- CNI Config:

```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "__KUBERNETES_NODE_NAME__",
      "mtu": __CNI_MTU__,
      "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "__KUBECONFIG_FILEPATH__"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}
```

**Comment by Ferroman** [comment]
I have the same issue.

We getting kubelet alert on limit of pods on some nodes because there are a lot of pods weren't removed and stuck in "Not ready state".

Calico version: v3.14.0 
Orchestrator version: Kubernetes v1.16.4
OS: CentOS 7 with Kernel 5.7.0
Container Runtime: containerd v1.3.4
CNI Config:
```
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "warning",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
```
Has a lot of same-looking logs from the "zombie" pods:
```
kubelet[3755]: E1016 08:37:41.008987    3755 kuberuntime_gc.go:170] StopPodSandbox "xxxxxxxxxxx" from runtime service failed: rpc error: code Unknown desc = failed to destroy network for sandbox "xxxxxxxxxxxxxxxxxxxxxxxx": WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(xxxxxxxxxxx/ip--x--x--x--x.ec2.internal-k8s-mongo--0-eth0)" not found
kubelet[3755]: E1016 08:37:41.008942    3755 remote_runtime.go:128] Failed to stop sandbox "xxxxxxxxx" before removing: rpc error: code = Unknown desc = failed to destroy network for sandbox "xxxxxxxxxx": WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(xxxxxxx/ip--x--x--x--x.ec2.internal-k8s-mongo--0-eth0)" not found"
containerd[3545]: time="2020-10-16T08:37:41.008730841Z" level=error msg="StopPodSandbox for \"8a4c2bd1fd58bc85ba07a
```

**Comment by eplightning** [comment]
Hit that issue myself. The commit that broke it seems to be https://github.com/projectcalico/cni-plugin/commit/212b84b61e73dd2a64da0524a42be33e04cb31eb

```
if _, err = calicoClient.WorkloadEndpoints().Delete(ctx, epIDs.Namespace, epIDs.WEPName, options.DeleteOptions{}); err != nil {
		if _, ok := err.(cerrors.ErrorResourceDoesNotExist); ok {
			// Log and proceed with the clean up if WEP doesn't exist.
			logger.WithField("WorkloadEndpoint", epIDs.WEPName).Info("Endpoint object does not exist, no need to clean up.")
		} else {
			return
		}
	}
```

The _err_ doesn't get cleared in case of _ErrorResourceDoesNotExist_ so it gets returned to CRI which fails StopPodSandbox call.

**Comment by caseydavenport** [comment]
Well, that's my bad! Thanks for tracking that down.

Here's a fix: https://github.com/projectcalico/cni-plugin/pull/1008

**Comment by haslersn** [comment]
Is the fix contained in Calico v3.18.1? With Calico v3.18.1, I still get such errors in my kubelet Log:

```
Mar 24 19:24:19 kube02 kubelet[1250]: E0324 19:24:19.710424    1250 remote_runtime.go:140] StopPodSandbox "85e72dd730e1f6d2ea488adb8fe33678f9b25f9105b0edd7eca0b3f7e641259e" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "85e72dd730e1f6d2ea488adb8fe33678f9b25f9105b0edd7eca0b3f7e641259e": WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(mysql-operator/kube02-k8s-presslabs--mysql--operator--0-eth0)" not found
Mar 24 19:24:19 kube02 kubelet[1250]: E0324 19:24:19.710465    1250 kuberuntime_gc.go:176] Failed to stop sandbox "85e72dd730e1f6d2ea488adb8fe33678f9b25f9105b0edd7eca0b3f7e641259e" before removing: rpc error: code = Unknown desc = failed to destroy network for sandbox "85e72dd730e1f6d2ea488adb8fe33678f9b25f9105b0edd7eca0b3f7e641259e": WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(mysql-operator/kube02-k8s-presslabs--mysql--operator--0-eth0)" not found
```

Or will the error continue to be printed even after upgrading Calico from an earlier version?

**Comment by caseydavenport** [comment]
I would expect this particular fix to be in v3.18.0+

>  WorkloadEndpoint.crd.projectcalico.org 

This is not even a real thing. There is no WorkloadEndpoint CRD - I wonder what's going on here...

@haslersn could you raise another issue describing your scenario / version / install method and any other relevant information?

@eplightning @Ferroman @muffin87 have you guys had a chance to see if your issues were resolved with an upgrade to v3.18? trying to decide if this is something different.

**Comment by eplightning** [comment]
Upgraded and it's still there:
```
E0407 21:03:52.108836  241114 remote_runtime.go:143] StopPodSandbox "fcf9854ed3839822c1d0d8493a33d06a0a161ecdcb0820493d6107ab4681e5af" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "fcf9854ed3839822c1d0d8493a33d06a0a161ecdcb0820493d6107ab4681e5af": WorkloadEndpoint.crd.projectcalico.org "WorkloadEndpoint(kube-system/kube--worker0-k8s-hcloud--csi--controller--0-eth0)" not found
```


Just noticed that error I pointed out in my previous comment wasn't really relevant to Kubernetes - which happens to have dedicated codepath and returns from that function earlier:
https://github.com/projectcalico/cni-plugin/blob/f73028f8c4b6327826b3d2cd5351706c903786d3/pkg/plugin/plugin.go#L585

I think this PR fixed this properly but that's only my guess: https://github.com/projectcalico/libcalico-go/pull/1363

**Comment by haslersn** [comment]
@eplightning Thanks. In which Calico version will this fix be available?

**Comment by muffin87** [comment]
@caseydavenport we tried 3.18.0 and the problem is still there.

**Comment by caseydavenport** [comment]
The second fix will be available in v3.19.0, which will be out in the next few weeks. I will also back-port so that this ends up in the next v3.18 patch release.

**Comment by winkee01** [comment]
I already reset my cluster, and I still can not remove the pods

**Comment by kkmaslowski** [comment]
@caseydavenport still have the same issue on rke2 version v1.23.7+rke2r2:



```
ERRO[2022-11-09T10:35:12.318231367+01:00] StopPodSandbox for "56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99" failed  error="failed to destroy network for sandbox \"56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://[10.53.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.53.0.1:443: i/o timeout"
E1109 10:35:12.318658   15864 remote_runtime.go:245] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://[10.53.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.53.0.1:443: i/o timeout" podSandboxID="56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99"
E1109 10:35:12.318707   15864 kuberuntime_gc.go:176] "Failed to stop sandbox before removing" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://[10.53.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.53.0.1:443: i/o timeout" sandboxID="56c29bcddb86a03e8bd78b1c41a9770f596b438b49e5afb4f4461d4c004ffe99"
INFO[2022-11-09T10:35:12.319028349+01:00] StopPodSandbox for "fce9ab116868723cef88a9f4b0ac6c4719f6819060fd53c19a6f068b7f6a28d6" 

```
