### ISSUE TITLE
calico-node / felix health check fails: "aws-source-destination-check"

### ISSUE THREAD

**Issue by TamasSzigeti** [projectcalico/calico#4154]
Hi, I've installed calico networking on EKS following [the simple instructions here](https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks). Everything seems to work, but calico-node health check keeps failing.

Please advise, I'm not a pro in this area, and I couldn't find anything relevant.

## Expected Behavior

Health check passing

## Current Behavior
```
Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
```

The log from the calico-node pod:
```
[INFO][39] felix/int_dataplane.go 1300: Applying dataplane updates
[INFO][39] felix/ipsets.go 223: Asked to resync with the dataplane on next update. family="inet"
[INFO][39] felix/ipsets.go 306: Resyncing ipsets with dataplane. family="inet"
[INFO][39] felix/ipsets.go 356: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.308558ms
[INFO][39] felix/int_dataplane.go 1314: Finished applying updates to dataplane. msecToApply=1.636869
[INFO][38] monitor-addresses/startup.go 756: Using autodetected IPv4 address on interface eth0: 192.168.68.211/19
[WARNING][39] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
[WARNING][39] felix/health.go 154: Health: not ready
[WARNING][39] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
```

This source/dest check seems to be turned off on the ENI.

## Your Environment

Cluster was just set up via eksctl, running k8s 1.18, also running cluster autoscaler and ingress-nginx

Thank you in advance

**Comment by seh** [comment]
This same problem came up in [this discussion in the "install" Slack channel](https://calicousers.slack.com/archives/CPTH1KS00/p1605101267217500).

**Comment by TamasSzigeti** [comment]
From Slack:
---
**lrobson**
After doing a bit of investigation, there appears to be a bug here.  We are working on it.  In the meantime, the workaround would be to remove these lines:
```
            # Disable AWS source-destination check on nodes.
            - name: FELIX_AWSSRCDSTCHECK
              value: Disable
```
from https://docs.projectcalico.org/manifests/calico-vxlan.yaml
before applying it.
If you've already applied it, edit the calico-node daemonset and delete that env var (edited) 
---
Thank you

**Comment by lmm** [comment]
Thanks for following up @TamasSzigeti - the latest version of the manifest now has that change (from https://github.com/projectcalico/calico/pull/4153)

**Comment by seh** [comment]
The problem lies between Felix's _dataplane/driver.go_ file and _projectcalico/libcalico-go_'s _lib/health/health.go_ file.

In the former's [`StartDataplaneDriver` function](https://sourcegraph.com/github.com/projectcalico/felix@ce40abb9cef32303953e10f1d71c65059d52065e/-/blob/dataplane/driver.go#L47-L346), we [register the health reporter](https://sourcegraph.com/github.com/projectcalico/felix@ce40abb9cef32303953e10f1d71c65059d52065e/-/blob/dataplane/driver.go#L326) for the ENI source/destination check maintenance. There, we note that the nominated "aws-source-destination-check" effort is both live and healthy.

Doing so registers this reporter with [an initial `health.HealthReport` of both live and healthy](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L109), but with [a latest report of just live, **but not healthy**](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L111).

Each time that a reporter checks in with a new report, we never update the `reporterState.reports` field; [we only ever update the `reporterState.latest` field](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L132-L135) when a new report differs from the most recent (previously "latest") report.

When [`(*HealthAggregator).Summary`](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L172-L202) inspects its contributing reporters' state, calling on [`(*reporterState).HasReadinessProblem`](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L50-L59), we see the problem:
- The current value of the `reporterState.reports.Ready` is true, so [we skip line 52](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L51-L52).
- The reporter for "aws-source-destination-check" has no timeout, so [we skip line 56](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L54-L56).
- The `reporterState.latest` field still holds [that initial value supplied by default by `(*HealthAggregator).RegisterReporter` as live but not healthy](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L111). The `health.HealthReport.Ready` field is false (still the zero value), so [`(*reporterState).HasReadinessProblem` returns true](https://sourcegraph.com/github.com/projectcalico/libcalico-go@master/-/blob/lib/health/health.go#L58).

Let's now go back over to `StartDataplaneDriver`. Our spawned goroutine tries to disable the ENI's source/destination check once. Only if it fails do [we update the health reporter](https://sourcegraph.com/github.com/projectcalico/felix@ce40abb9cef32303953e10f1d71c65059d52065e/-/blob/dataplane/driver.go#L334). When all is well, the health reporter stays in its initial state: a recent report indicating that it's live and ready, but its latest report only indicating that it's live.

I can see a couple of ways of fixing this:
1. When we update the ENI source/destination check successfully, report that we're both live **and ready**.  
  For clarity, we should probably register our initial state as only live and not ready, and not indicate that we're ready until we've disabled the check successfully.
1. Change `(*HealthAggregator).RegisterReporter` to set this reporter's latest health report to be equal to the value supplied in its "reports" parameter.  
  We set the`reporterState.latest` field to this "reports" argument today. We should also set the `reporterState.reports` field to this same value, or drop the `reporterState.reports` field entirely. It's not clear what the intended difference is between these two fields. The `(*reporterState).HasReadinessProblem` and `(*reporterState).HasLivenessProblem` methods consult both fields. They say, effectively, "If the initial state was not ready, we are ready. If we haven't had an update in too long, we are not ready. Otherwise, consult the latest report." Is that first condition's result backwards? 
  _[Time passes ...]_  
  Oh! Does the `reporterState.reports` field mean whether or not we ever report this state? Yes, that must be it. This would be far less confusing if we instead dedicated a couple of `bool` fields with clearer names. Given that, scratch this idea. I'll assume the intention in `(*HealthAggregator).RegisterReporter` was to consider the current process as implicitly live, but assume pessimistically that it's not yet ready until a report arrives saying so. Renaming some things here would help future readers deal with both of the health and readiness states being optional.

**Comment by seh** [comment]
Please see projectcalico/felix#2593.

**Comment by seh** [comment]
Thinking about this more, the patch we committed isn't enough.

We only try to adjust the source/destination check once. If we succeed, Felix reports that it's now ready. Otherwise, it remains unready forever. Since we continue to report that we're live, though, the kubelet won't restart the "calico-node" pod. That means that the pod sits there blocking other things that check for readiness of critical pods, such as the _kops rolling-update cluster_ command.

Instead, I'd prefer that we periodically retry to adjust the source/destination check until we finally succeed. It's possible that an administrator could have run _kops update cluster_ first, which sets the "calico-node" pods running (possibly having replaced the previous set of pods) where they'll try to adjust the source/destination checks, but the administrator has not yet run _terraform apply_ to grant to necessary permissions to the security group that governs the worker machines in the cluster. The "calico-node" pods that win that race would sit there forever, requiring the administrator to later run _kubect --namespace=kube-system rollout restart daemonset calico-node_, replacing any of the "calico-node" pods that lost the race unnecessarily.

I don't see a `context.Context` available in the `StartDataplaneDriver` function. That would be helpful for indicating that such a periodic attempt at adjusting the source/destination check should cease.

**Comment by fasaxc** [comment]
The idea behind going non-ready in general is that it stops a rolling update with one node "bad" rather than continuing to roll out to the whole cluster.  TBH, I think it might be overkill to gate on the src/dest check at all.  There isn't any "downstream" function that gets activated on the src/dest check, it's just that readiness is our only real feedback to the user that something is wrong and we can't realise the configuration that's been set.

**Comment by perezjasonr** [comment]
> From Slack:
> 
> **lrobson**
> After doing a bit of investigation, there appears to be a bug here. We are working on it. In the meantime, the workaround would be to remove these lines:
> 
> ```
>             # Disable AWS source-destination check on nodes.
>             - name: FELIX_AWSSRCDSTCHECK
>               value: Disable
> ```
> 
> from https://docs.projectcalico.org/manifests/calico-vxlan.yaml
> before applying it.
> If you've already applied it, edit the calico-node daemonset and delete that env var (edited)
> 
> Thank you

any update on this? were still using the above mentioned workaround to deal with this error

**Comment by seh** [comment]
> any update on this?

This was fixed by projectcalico/felix#2592, released via projectcalico/felix#2604 in Calico version 3.17.

**Comment by perezjasonr** [comment]
thanks for the update, so will this issue be closed then?

**Comment by seh** [comment]
I think we should close it. I lack permission to do so, though.

**Comment by mcorbin** [comment]
Hello,

I hit the same issue while migrating from Calico 3.17.2 to Calico 3.18.1.
I used the `calico-vxlan.yaml` file from the release and the calico-node pods were never ready:

```
2021-03-12 11:15:43.187 [WARNING][42] felix/health.go 154: Health: not ready
2021-03-12 11:15:43.721 [WARNING][42] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
2021-03-12 11:15:53.204 [WARNING][42] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
```

The default `calico-vxlan.yaml` file for 3.18.1 contains:

```
            # Disable AWS source-destination check on nodes.
            - name: FELIX_AWSSRCDSTCHECK
              value: Disable
```

I also had to remove this option in order to make calico-node start. So I think the issue is not solved yet.

**Comment by kron4eg** [comment]
Can confirm, using v3.18.1 and have `FELIX_AWSSRCDSTCHECK=Disable`, still running into the issue.

**Comment by kron4eg** [comment]
With removed `FELIX_AWSSRCDSTCHECK=Disable` node is able to start.

**Comment by mcorbin** [comment]
@caseydavenport Could you reopen the issue please ?

**Comment by mmarkoulis** [comment]
Issue and workaround apply to v3.19.1 also.

**Comment by perezjasonr** [comment]
This needs to be reopened.

/open

**Comment by theophileds** [comment]
I encountered the same issue using calico v3.19.2.
FELIX_AWSSRCDSTCHECK=Disable seems to fix it.

**Comment by SCLogo** [comment]
happened on calico 3.20. Any update?

**Comment by fasaxc** [comment]
Please create a new issue, it's likely to be something different.  If I had to guess, you've started your nodes without the required IAM permission for the AWS source dest check feature to work.  This could be a change in EKS to no longer grant that permission by default, for example.

The permission I'd expect us to need is `ModifyNetworkInterfaceAttribute` (and possibly `DescribeInstances` and `DescribeNetworkInterfaces`).

**Comment by mcorbin** [comment]
@fasaxc For me it seems to be the same issue. I do not use EKS at all in my case.

Steps to reproduce:

- I created a new Kubernetes cluster without any CNI installed (on Exoscale but I guess any provider can be used).
- I applied `calico-vxlan.yaml` from the latest Calico release (v3.21.0). The manifest contains:

```
            # Disable AWS source-destination check on nodes.
            - name: FELIX_AWSSRCDSTCHECK
              value: Disable
```

`calico-node` pods fail to start:

```
2021-11-18 10:06:28.555 [WARNING][87] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
2021-11-18 10:06:28.566 [WARNING][87] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
2021-11-18 10:06:28.566 [WARNING][87] felix/health.go 154: Health: not ready
```

I then remove the `FELIX_AWSSRCDSTCHECK` configuration from the manifest and reapplied it: `calico-node` pods are now running and ready.

**Comment by fasaxc** [comment]
@mcorbin That's a different issue.  The AWS source/dest check feature is _supposed_ to work on EKS.  The problem you have is that we've included that flag in the general vxlan manifest and it's an AWS-specific thing.  I've filed #5101 to track
