### ISSUE TITLE
SYN retransmission with calico ebpf when load balancer service has more than one pod to route to

### ISSUE THREAD

**Issue by sagor999** [projectcalico/calico#4712]
## Expected Behavior
Using LoadBalancer service, that has more than one pod that it routes to, should result in all connections being handled and accepted without SYN packet retransmission.

## Current Behavior
If I have a load balancer service, that has more than one pod that it can route the traffic to, there is a very high chance that initial connection will have a stall due to SYN retransmission. 
Used wireshark to confirm that SYN packet is being lost and being retransmitted multiple time until it actually works. 

If I only have one pod behind loadbalancer service, then everything works without any issues.

This is on bare-metal on prem k8s cluster, using MetalLB for load balancer allocation, in Layer 2 mode. (so external IP is announced from only one node).

Here is wireshark from the source node (10.196.39.141) that sends request to connect to target service (10.196.37.168) that is being announced by metalLB from the node (10.196.37.135).
Source node is outside of k8s cluster.
So this is wireshark capture from source node:
```
5 17.520604852 10.196.39.141 → 10.196.37.168 TCP 76 54386 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573466930 TSecr=0 WS=1024
6 18.547521962 10.196.39.141 → 10.196.37.168 TCP 76 [TCP Retransmission] 54386 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573467957 TSecr=0 WS=1024
7 20.563548464 10.196.39.141 → 10.196.37.168 TCP 76 [TCP Retransmission] 54386 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573469973 TSecr=0 WS=1024
8 20.563621016 10.196.37.168 → 10.196.39.141 TCP 76 80 → 54386 [SYN, ACK] Seq=0 Ack=1 Win=42840 Len=0 MSS=1440 SACK_PERM=1 TSval=4115550776 TSecr=1573469973 WS=1024
```

This is wireshark capture from the node(10.196.37.135) that is announcing load balancer service IP(10.196.37.168):
```
32 61.360425859 10.196.39.141 → 10.196.37.168 TCP 76 59922 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573882174 TSecr=0 WS=1024
33 62.390466866 10.196.39.141 → 10.196.37.168 TCP 76 [TCP Retransmission] 59922 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573883204 TSecr=0 WS=1024
34 64.406419784 10.196.39.141 → 10.196.37.168 TCP 76 [TCP Retransmission] 59922 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573885220 TSecr=0 WS=1024
35 68.630447926 10.196.39.141 → 10.196.37.168 TCP 76 [TCP Retransmission] 59922 → 80 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=1573889444 TSecr=0 WS=1024
36 68.630528854 10.196.37.168 → 10.196.39.141 TCP 76 80 → 59922 [SYN, ACK] Seq=0 Ack=1 Win=42840 Len=0 MSS=1440 SACK_PERM=1 TSval=4115970264 TSecr=1573889444 WS=1024
37 68.630586379 10.196.39.141 → 10.196.37.168 TCP 68 59922 → 80 [ACK] Seq=1 Ack=1 Win=29696 Len=0 TSval=1573889444 TSecr=4115970264
38 68.630670266 10.196.39.141 → 10.196.37.168 HTTP 161 GET / HTTP/1.1 
39 68.630679455 10.196.37.168 → 10.196.39.141 TCP 68 80 → 59922 [ACK] Seq=1 Ack=94 Win=43008 Len=0 TSval=4115970264 TSecr=1573889444
40 68.631282817 10.196.37.168 → 10.196.39.141 HTTP 412 HTTP/1.1 200 OK  (text/html)
41 68.631311663 10.196.39.141 → 10.196.37.168 TCP 68 59922 → 80 [ACK] Seq=94 Ack=345 Win=30720 Len=0 TSval=1573889445 TSecr=4115970265
42 68.631422146 10.196.39.141 → 10.196.37.168 TCP 68 59922 → 80 [FIN, ACK] Seq=94 Ack=345 Win=30720 Len=0 TSval=1573889445 TSecr=4115970265
43 68.631535757 10.196.37.168 → 10.196.39.141 TCP 68 80 → 59922 [FIN, ACK] Seq=345 Ack=95 Win=43008 Len=0 TSval=4115970265 TSecr=1573889445
44 68.631567802 10.196.39.141 → 10.196.37.168 TCP 68 59922 → 80 [ACK] Seq=95 Ack=346 Win=30720 Len=0 TSval=1573889445 TSecr=4115970265
```

So on the node that is announcing our IP, it seems like it receives all those SYN retransmissions. Which to me means that packet is somehow getting misrouted or lost somewhere inside calico. 

The moment I remove second pod (so that load balancer service only routes traffic to 1 pod, instead of 2), SYN retransmissions disappear. 

Changing externalTrafficPolicy on load balancer service from Local to Cluster or vise versa has no effect on this. 

If you change your deployment to deploy your pods to just one node, instead of spreading it over two nodes, then issue doesn't reproduce. 
There is also no traffic hitting the second node, so it is not the issue with metalLB. All traffic correctly lands on the node that announces external IP.

## Steps to Reproduce (for bugs)
0. Create a two node cluster that uses MetalLB in layer 2 mode to be able to allocate load balancer service.
1. Create a simple container that can respond with "Hello World" to any http request. Can be anything, not important.
2. Create a load balancer service that routes traffic to that pod. MetalLB will announce external IP from one of the nodes.
3. Scale deployment to 1 pod.
4. Attempt to connect to your service via ExternalIP of your load balancer service. Notice that everything is working and connection is established right away.
5. Now scale your deployment to 2 pods. In my tests I had a second pod allocated on second node. (Important, issue doesn't reproduce if both pods are on the same node).
6. Attempt to establish connection (might need several retries to repro) and notice that all of a sudden it takes longer to establish connection. If wireshark is running, you will see SYN packet retransmission. After X attempts eventually connection will be established. Usually X is 1 or 2, but sometimes can be larger (in my worst case it took 70 seconds to establish connection).

## Context
We had an issue with random timeouts when external service would attempt to connect to a service that was hosted in the k8s cluster. After a month of debugging, finally found out what was causing this. 

## Your Environment
* Calico version: 3.18.1 running in eBPF mode without kube proxy (calico runs as replacement of kube proxy)
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.18.18
* Operating System and version: Ubuntu 18.04 with kernel 5.4

We have another on prem cluster, that has similar setup (metalLB in layer 2 and calico) but calico version 3.15.1, without eBPF, and cluster runs with kube-proxy in iptables mode. That issue is not reproducible in that cluster. 
Which makes me think that this is an issue with calico in ebpf in kube-proxy replacement mode. 

Please let me know if I can provide more information. It is very easy to reproduce this on my end. 

Thank you

**Comment by sagor999** [comment]
Could this be potentially be fixed in calico 3.19.0 with this:
https://github.com/projectcalico/felix/pull/2675
?

**Comment by sagor999** [comment]
This also might be related to a similar issue here:
https://github.com/projectcalico/calico/issues/4290

**Comment by caseydavenport** [comment]
ping @fasaxc  / @tomastigera

**Comment by sagor999** [comment]
We tried to upgrade to 3.19 version, but still had the same problem.

**Comment by tomastigera** [comment]
> Could this be potentially be fixed in calico 3.19.0 with this:
> [projectcalico/felix#2675](https://github.com/projectcalico/felix/pull/2675)
> ?

That fix was related to network issues external to the eBPF platform, e.g packets lost on the way towards the cluster. You are saying that the issue still exists in 3.19 so it is like unrelated (good to know :) )

**Comment by tomastigera** [comment]
I will try to reproduce the issue. It may be related to some other issues that are being currently worked on. Might be that the balancer does something we do not expect. It is weird that traffic eventually goes through :thinking:

**Comment by tomastigera** [comment]
I believe that this is also a repro of #4431 , I am closing this as a duplicate. We have a RCA for #4431 now. Pls, reopen if the fix for the duplicate does not work for your case.

**Comment by tomastigera** [comment]
I believe that this is also a repro of #4431 , I am closing this as a duplicate. We have a RCA for #4431 now. Pls, reopen if the fix for the duplicate does not work for your case.
