### ISSUE TITLE
calico-kube-controllers pending since not tolerate the "node-role.kubernetes.io/control-plane"

### ISSUE THREAD

**Issue by vincent-pli** [projectcalico/calico#6087]
Follow the guide there: https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart

after install calico, the `calico-kube-controllers` is pending, since it not tolerate the taints `node-role.kubernetes.io/control-plane` on the node.

The `node-role.kubernetes.io/control-plane` is introduce in kubernetes v1.20 and my k8s version is v1.24.0

After remove the taint from the node, it works

**Comment by nonghinh** [comment]
I have the same issue

**Comment by NeilW** [comment]
Same here - using the manifest for installation.

**Comment by tmjd** [comment]
Thank you for bringing this to our attention, according to https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane that is a replacement for `node-role.kubernetes.io/master` taint, so we probably need to add a toleration for anywhere we tolerated the master taint.

For anyone that runs into this before this is addressed you should be able to define a toleration in the Installation resource (applied initially from `custom-resources.yaml`) by adding a spec.controlPlaneTolerations section. For example taking the Installation resource from the quickstart guide:
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
  controlPlaneTolerations:
    - key: "node-role.kubernetes.io/control-plane"
      effect: NoSchedule
```

**Comment by caseydavenport** [comment]
> Is there something I can do to remedy this?

@bsau3130 see the comment directly above yours. It includes a way to configure Calico to tolerate this taint.

**Comment by new-mikha** [comment]
> I was running into that very same issue; I wanted to report that in order to get the cluster up and running I have had to define a second similar toleration
> 
> ```
>   controlPlaneTolerations:
>     - key: node-role.kubernetes.io/control-plane
>       effect: NoSchedule
>     - key: node-role.kubernetes.io/master
>       effect: NoSchedule
> ```

Same for me.
I found that without toleration for `...master`, the `calico-typha...` node is not starting up:
![STATUS RESTARTS](https://user-images.githubusercontent.com/5769929/179913441-2837c7ae-3b13-4cf0-9f43-43f35726d67e.png)

After looking into the pod details, it says that yes it doesn't want to start because of this:
kubectl describe pods/calico-typha-74dcf59cbf-ffcv2 -n calico-system
```
…
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  53s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated
taint {node-role.kubernetes.io/master: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful
 for scheduling.
```

**At the same time, the control plane node was marked as "Ready" by "kubectl get nodes", so tbh I'm not entirely sure if it was the right thing to add this toleration or not.**

Anyway, after adding the toleration above, it all worked like a charm.

**Comment by new-mikha** [comment]
One thing to add, although most probably it was an unrelated glitch... I did quite a few tries until passed through the CNI phase, and I think the toleration's timeout on k8s DNS pods `...not-ready:NoExecute op=Exists for 300s` played badly. So, for those who applied all the above and it still doesn't work - try to restart the k8s service (or the whole machine), in my case it helped after I was too slow with installing calico. A bit hard to reproduce, to this bit of advice might be unreliable.

Here is description for a system `coredns`pod:
![Pasted Graphic 3](https://user-images.githubusercontent.com/5769929/179915961-973cf4cf-b5fc-4780-9ef3-296d857aff43.png)
