### ISSUE TITLE
Calico operator installation object stuck on deleting

### ISSUE THREAD

**Issue by rshiva777** [projectcalico/calico#9066]
I am trying to delete calico installation object, but it keep on stuck deleting

## Expected Behavior

Calico installation object should be deleted

## Current Behavior

Calico installation object is not getting deleted

## Possible Solution

by removing finalizer from the installation object, it is being deleted

## Steps to Reproduce (for bugs)

1. helm install calico projectcalico/tigera-operator --version v3.27.0
2. kubectl delete installations.operator.tigera.io/default

## Context

Unable to delete the calico installation

## Your Environment

* Calico version: v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.28
* Operating System and version: Amazon Linux
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> by removing finalizer from the installation object, it is being deleted

I wouldn't recommend doing this manually, it will result in resources being left in the cluster. The operator removes this itself when it has successfully cleaned up after itself - most likely it is failing to clean up one of its resources and thus is waiting before removing the finalizer. 

I'd recommend upgrading to v3.28.0 - we fixed a number of issues related to termination in that release, so it's quite possible you're running in to one of those.

**Comment by ujjwalsoni1903** [comment]
We are also facing issues with Calico 3.27.4. We tried upgrading to Calico 3.28.0, but unfortunately, the issue persists.

Below are the environment details:

Calico versions: v3.27.4 & v3.28.0
Orchestrator version (e.g., Kubernetes, Mesos, rkt): EKS-1.28
Operating System and version: Amazon Linux

**Comment by caseydavenport** [comment]
@ujjwalsoni1903 @rshiva777 Do you have the Calico API server running? i.e., does this show anything?

```
kubectl get apiservers.operator.tigera.io
```

If so, you need to delete that as well in order for the Installation to terminate:

```
kubectl delete apiserver default
```

If that's not the problem, could you show the output of the following commands both prior to deleting the Installation as well as after?

```
kubectl get installation -o yaml
kubectl get apiservers -o yaml
kubectl get tigerastatus -o yaml
```

As well as the logs from the operator pod after deleting the Installation?

**Comment by ujjwalsoni1903** [comment]
@caseydavenport , Thanks for your reply !! 

I have checked after deleting apiserver. Still we need to remove finalizer from the installation object.

please find attached output of below commands:

```
kubectl get installation -o yaml
kubectl get apiservers -o yaml
kubectl get tigerastatus -o yaml
```
[output.txt](https://github.com/user-attachments/files/16540314/output.txt)

**Comment by caseydavenport** [comment]
That all seems reasonable to me.

I think output from _after_ deleting might be helpful, as well as logs from the tigera-operator pod.

**Comment by tomastigera** [comment]
@ujjwalsoni1903 @rshiva777 any new info?

**Comment by ujjwalsoni1903** [comment]
@tomastigera no. Need to circle back on the issue
